Iter5
LobovVit/metric-collector pull request #11
Opened 2024-01-01 22:47 UTC by LobovVit

iter5

2024-01-10 08:39 UTC, Nikscorp requested changes
Привет!

Хорошая работа, мне понравилась организация кода и использование html шаблонов.

Есть несколько замечаний, которые стоит исправить.

2024-01-10 08:39 UTC, Nikscorp commented on go.mod
> +go 1.21.4
давай выставим просто 1.21, требовать минорную версии — это слишком

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/skeduller/send.go
> +		//client := &http.Client{}
код отправлемый на ревью должен быть свободен от лишних комментариев вроде закомментированного кода.

Если это задел на будущее — все равно лучше удалить и потом восстановить из гита

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +		for now := range time.Tick(time.Second * time.Duration(readTime)) {
минорное замечание, но тикер тут утекает. Вроде несложно будет его закрыть

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +	wg.Wait()
по сути `defer wg.Done()` нигде не делается.

Хочется добавить graceful shutdown хоть в каком то виде. Предлагаю создать контекст, отменяемый sigint / sigterm через `signal.NotifyContext` и читать его в цикле select-ом вместе с тикером. Контекст также стоит передавать в сетевые вызовы.

При завершении контекста — делать возврат из горутины и wg.Done (лучше defer-ом)

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +			fmt.Printf("sendTime:%v\n", now)
лучше всегда использовать log, fmt.Print — несерьезно

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +	rw := sync.Mutex{}
rw неудачное название — по нему кажется, что ты используешь rwMutex

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/skeduller/send.go
> +var client = resty.New()
лучше обойтись без глобальных переменных, давай сделаем структуру и метод

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/skeduller/send.go
> +			os.Exit(1)
давай отсюда будем ошибку возвращать, точка выхода предпочтительно должна быть только одна

2024-01-10 08:39 UTC, Nikscorp commented on cmd/server/main.go
> +	mux.Get("/", handlers.AllMetricsHandler)
я бы перенес настройку роутера в пакет handlers, а сами хэндлеры сделал приватными

2024-01-10 08:39 UTC, Nikscorp commented on internal/agent/metrics/getMetrics.go
> +package metrics
смущает, что много файлов названы в camelCase, обычно в go так обычно не делают

2024-01-10 08:39 UTC, Nikscorp commented on internal/server/domain/actions/storageInterface.go
> +var store = StorInterface(storage.GetStorage())
снова глобальные переменные — это плохо, всегда сделать структуры

2024-01-10 08:39 UTC, Nikscorp commented on internal/server/domain/actions/storageInterface.go
> +type StorInterface interface {
в имени интерфейса не должно быть слова интерфейс, почитай конвенции прикрепленные к урокам

2024-01-10 08:39 UTC, Nikscorp commented on internal/server/domain/storage/memStorage.go
> +	retCounter := make(map[string]string)
при создании мап, размер которых ты точно знаешь, лучше делать преаллокацию нужного размера. Например `make(map[string]string, len(ms.Counter))`

2024-01-10 08:39 UTC, Nikscorp commented on internal/server/domain/storage/memStorage.go
> +			return "", errors.New("NotFound")
а вот тут как раз следует сделать глобальную переменную `ErrNotFound` и возвращать ее, возможно врапая ее ключом, который не был найден

2024-01-10 08:39 UTC, Nikscorp commented on internal/server/handlers/allmetricshandler.go
> +		return []byte("Err Parse" + err.Error())
все же функция должна возвращать ошибку, чтобы в подобных кейфах вернуть 500

2024-01-10 08:39 UTC, Nikscorp commented on internal/server/domain/storage/memStorage.go
> +	gauge   map[string]float64
тут не хватает rw мьютекса для организации конкурентного доступа

2024-01-11 19:23 UTC, LobovVit commented on internal/server/domain/storage/memStorage.go
> +	gauge   map[string]float64
сделал - в методах структуры "лочусь" на чтение в читающих и полностью в пишущих

2024-01-11 19:23 UTC, LobovVit commented on internal/server/handlers/allmetricshandler.go
> +		return []byte("Err Parse" + err.Error())
сделал - и 500-ку тоже добавил

2024-01-11 19:23 UTC, LobovVit commented on internal/server/domain/storage/memStorage.go
> +			return "", errors.New("NotFound")
сделал функцию возвращающую ошибку с параметрами ошибочного ключа

2024-01-11 19:23 UTC, LobovVit commented on internal/server/domain/storage/memStorage.go
> +	retCounter := make(map[string]string)
добавил преаллокацию

2024-01-11 19:23 UTC, LobovVit commented on internal/server/domain/actions/storageInterface.go
> +type StorInterface interface {
переименовал

2024-01-11 19:23 UTC, LobovVit commented on internal/server/domain/actions/storageInterface.go
> +var store = StorInterface(storage.GetStorage())
вот тут как ни крутил - не могу понять как избавится - данные одного и того же экземпляра структуры должны быть доступны из разных методов пакета (при этом какой из них заработает первый - неизвестно) - если пытаться инициировать создание экземпляра структуры в каждой функции то не понятно как получит доступ к ней из другой 

често я чет не понял - буду копать дальше - но пока в тупике

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/metrics/getMetrics.go
> +package metrics
привел регистр д lower

2024-01-11 19:23 UTC, LobovVit commented on cmd/server/main.go
> +	mux.Get("/", handlers.AllMetricsHandler)
перенес в router.go (пакет handlers)

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/skeduller/send.go
> +			os.Exit(1)
сделал

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/skeduller/send.go
> +var client = resty.New()
создал структуру restyClient  и ee метод new()

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/skeduller/timer.go
> +	rw := sync.Mutex{}
при уходе от горутин (замечание про graceful shutdown ) - оказалось не нужны - убрал

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/skeduller/timer.go
> +			fmt.Printf("sendTime:%v\n", now)
поменял на log

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/skeduller/timer.go
> +	wg.Wait()
graceful shutdown - постарался реализовать при этом ушел от создания своих горутин

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/skeduller/timer.go
> +		for now := range time.Tick(time.Second * time.Duration(readTime)) {
убрал  через  defer sendTicker.Stop()

2024-01-11 19:23 UTC, LobovVit commented on internal/agent/skeduller/send.go
> +		//client := &http.Client{}
почистил лишние комментарии

2024-01-11 19:23 UTC, LobovVit commented on go.mod
> +go 1.21.4
подкорректировал

2024-01-15 20:28 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +	wg.Wait()
хм, честно говоря уходить от concurrency тут сомнительно, но раз в курсе их пока формально не было — резолвлю

2024-01-15 20:30 UTC, Nikscorp commented on internal/server/domain/actions/storageInterface.go
> +var store = StorInterface(storage.GetStorage())
пока в тупике — отправлять на повторное ревью не стоит) Лучше задать вопрос в чате.

Инициализация производится в функции-конструкторе, которая возвращает указатель на созданную структуру, где все поля проинициализированы. Методы уже используют готовые к работе поля

2024-01-15 20:46 UTC, Nikscorp requested changes
Привет!

Ключевое замечание про переход от функций и глобальных переменных к структурам не было исправлено.

Добавил еще несколько замечаний, прошу исправить.

2024-01-15 20:46 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +func StartTimer(ctx context.Context, readTime int64, sendTime int64, endPoint string) {
Start обычно подразумевает неблокирующую функцию. Это скорее `RunTimer` или даже `RunAgent`

2024-01-15 20:46 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +			log.Printf("shutdown\n")
\n не нужен, `log.Printf` внезапно и сам его подставит

2024-01-15 20:46 UTC, Nikscorp commented on internal/agent/skeduller/timer.go
> +				return
return тут лучше убрать, вредил одна ошибка говорит о том, что следует стопать агента

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/config/config.go
> +var instance *Config
все еще глобальная переменная, зачем?

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/config/config.go
> +	instance = &Config{}
instance лучше переименовать в config

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/config/config.go
> +		log.Fatal(err)
ранее уже писал, что лучше сделать единую точку выхода, а тут лучше вернуть ошибку просто

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/domain/actions/getall.go
> +	return store.storage.GetAll(), nil
лишняя пустая строка в теле функции

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/domain/actions/getsingle.go
> +
и тут

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/domain/storage/memstorage.go
> +	return fmt.Errorf("not found metric type:\"%v\" with name:\"%v\"", tp, name)
так с ошибками обычно не работают. Советую прочитать https://github.com/uber-go/guide/blob/master/style.md#errors и поправить

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/handlers/allmetricshandler.go
> +	} else {
лучше не создавать большую вложенность. Сделай return в if-е, тогда и else писать не придется. Вообще else — лучше по возможности избегать

2024-01-15 20:46 UTC, Nikscorp commented on internal/server/domain/actions/storageInterface.go
> +var store = StorInterface(storage.GetStorage())
в общем это ключевое замечание — у тебя очень много кода, который вместо структур и методов использует функции и глобальные переменные. Это нужно обязательно исправлять

2024-01-16 14:06 UTC, LobovVit commented on internal/agent/skeduller/timer.go
> +		for now := range time.Tick(time.Second * time.Duration(readTime)) {
Убрал

2024-01-16 14:11 UTC, LobovVit commented on internal/agent/skeduller/timer.go
> +func StartTimer(ctx context.Context, readTime int64, sendTime int64, endPoint string) {
исправил

2024-01-16 14:11 UTC, LobovVit commented on internal/server/domain/storage/memStorage.go
> +	gauge   map[string]float64
исправил

2024-01-16 14:11 UTC, LobovVit commented on internal/server/domain/actions/storageInterface.go
> +var store = StorInterface(storage.GetStorage())
почистил пустые строки

2024-01-16 14:11 UTC, LobovVit commented on internal/agent/metrics/getMetrics.go
> +package metrics
почистил пустые строки

2024-01-16 14:11 UTC, LobovVit commented on internal/server/config/config.go
> +		log.Fatal(err)
исправил

2024-01-16 14:11 UTC, LobovVit commented on cmd/server/main.go
> +	mux.Get("/", handlers.AllMetricsHandler)
переименовал

2024-01-16 14:11 UTC, LobovVit commented on internal/agent/skeduller/send.go
> +			os.Exit(1)
убрал

2024-01-16 14:12 UTC, LobovVit commented on internal/agent/skeduller/send.go
> +var client = resty.New()
убрал return + подсчет кол-ва чтений метрик при ошибке не обнуляю

2024-01-16 14:12 UTC, LobovVit commented on go.mod
> +go 1.21.4
переименовал

2024-01-16 14:19 UTC, LobovVit commented on internal/server/config/config.go
> +	instance = &Config{}
исправил

2024-01-16 14:19 UTC, LobovVit commented on internal/server/config/config.go
> +var instance *Config
убрал

2024-01-16 14:19 UTC, LobovVit commented on internal/agent/skeduller/timer.go
> +			log.Printf("shutdown\n")
убрал

2024-01-16 14:20 UTC, LobovVit commented on internal/server/domain/actions/getall.go
> +	return store.storage.GetAll(), nil
убрал пустые строки

2024-01-16 14:20 UTC, LobovVit commented on internal/server/domain/actions/getsingle.go
> +
убрал пустые строки

2024-01-16 14:21 UTC, LobovVit commented on internal/server/domain/storage/memstorage.go
> +	return fmt.Errorf("not found metric type:\"%v\" with name:\"%v\"", tp, name)
переделал

2024-01-16 14:21 UTC, LobovVit commented on internal/server/handlers/allmetricshandler.go
> +	} else {
исправил

2024-01-18 06:26 UTC, Nikscorp requested changes
Привет!

Хорошая работа!

Уже очень хочется поставить аппрув, но пока еще остались несколько мест, которые сильно бросаются в глаза. Давай их поправим, думаю еще одной итерации нам хватит.

2024-01-18 06:26 UTC, Nikscorp commented on cmd/agent/main.go
> +	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGHUP, syscall.SIGTERM, syscall.SIGABRT)
stop -> cancel. Обычно ее всегда называют `cancel`

2024-01-18 06:26 UTC, Nikscorp commented on cmd/agent/main.go
> +	agent := app.NewAgent(cfg, ctx)
контекст принято передавать первым аргументом и не в конструктор, а скорее в run. В саму структуру контекст обычно не прикапывают

2024-01-18 06:26 UTC, Nikscorp commented on internal/agent/app/agent.go
> +			log.Printf("send")
в данном моменте скорее уже sent

2024-01-18 06:26 UTC, Nikscorp commented on internal/agent/app/agent.go
> +			return err
ошибки не врапаются почти нигде, а врапать их стоит почти всегда :)

2024-01-18 06:26 UTC, Nikscorp commented on internal/agent/app/resty.go
> +func (rc *restyClient) new() *restyClient {
конструктор должен быть функцией, а не методом. `sender := NewRestyClient()` и готово. Но в данном случае вообще этот файл не нужен.

Ты здесь ничего кроме `resty.New()` не используешь, а его можно вызвать в конструкторе агента, кстати сразу проставив, например baseURL и метод

2024-01-18 06:26 UTC, Nikscorp commented on internal/agent/app/agent.go
> +	sender.new()
не стоит пересоздавать resty клиента на каждый запрос, это неэффективно — прикопай его в структуру самого агента

2024-01-18 06:26 UTC, Nikscorp commented on internal/server/domain/storage/memstorage.go
> +		} else {
все эти ветки else и default можно заменить на единственную строку `return "", notFoundMetricError{tp, name}` после switch-а

2024-01-18 06:26 UTC, Nikscorp commented on internal/server/server/allmetricshandler.go
> +	reader := new(strings.Builder)
reader очень плохое имя для имплементации `io.Writer` интерфейса

2024-01-18 06:26 UTC, Nikscorp commented on internal/server/domain/storage/memstorage.go
> +	return &MemStorage{make(map[string]float64), make(map[string]int64), sync.RWMutex{}, sync.RWMutex{}} //Storage
лучше использовать именованные поля при инициализации структур. Мьютексы инициализировать не обязательно, они и сами произициализируются

2024-01-18 06:26 UTC, Nikscorp commented on internal/agent/metrics/getMetrics.go
> +package metrics
почему-то имя файла все еще в camelCase)

2024-01-18 08:01 UTC, LobovVit commented on internal/agent/metrics/getMetrics.go
> +package metrics
поправил

2024-01-18 08:01 UTC, LobovVit commented on internal/server/domain/storage/memstorage.go
> +	return &MemStorage{make(map[string]float64), make(map[string]int64), sync.RWMutex{}, sync.RWMutex{}} //Storage
поправил

2024-01-18 08:01 UTC, LobovVit commented on internal/server/server/allmetricshandler.go
> +	reader := new(strings.Builder)
переименовал

2024-01-18 08:07 UTC, LobovVit commented on internal/server/domain/storage/memstorage.go
> +		} else {
поправил

2024-01-18 08:56 UTC, LobovVit commented on cmd/agent/main.go
> +	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGHUP, syscall.SIGTERM, syscall.SIGABRT)
переименовал

2024-01-18 08:56 UTC, LobovVit commented on cmd/agent/main.go
> +	agent := app.NewAgent(cfg, ctx)
Исправил

2024-01-18 08:57 UTC, LobovVit commented on internal/agent/app/agent.go
> +			log.Printf("send")
поправил

2024-01-18 08:58 UTC, LobovVit commented on internal/agent/app/agent.go
> +	sender.new()
сделал

2024-01-18 09:09 UTC, LobovVit commented on internal/agent/app/resty.go
> +func (rc *restyClient) new() *restyClient {
перенес в структуру агента , resty.go - удалил

2024-01-18 09:44 UTC, LobovVit commented on internal/agent/app/agent.go
> +			return err
добавил errors.Wrap(err, "текст")

2024-01-19 16:08 UTC, Nikscorp approved these changes
Привет!

Оставил еще несколько замечаний, но не считаю их сильно критичными.
Поэтому ставлю аппрув и принимаю работу.

Оставшиеся замечания все же прошу поправить и результат замерджить в main (master). Повторно данный инкремент присылать на ревью не нужно.

Хорошая работа!

2024-01-19 16:08 UTC, Nikscorp commented on cmd/agent/main.go
> +	"github.com/pkg/errors"
так, этот пакет уже несколько лет как deprecated, весь функционал есть в стандартной библиотеке — замени все `errors.Wrap` на `fmt.Errorf("some message: %w", err)

2024-01-19 16:08 UTC, Nikscorp commented on internal/agent/app/agent.go
> +				log.Printf("err sendRequest %v", err)
текст ошибки пишется с маленькой буквы, а вот logMessage обычно с большой

2024-01-19 19:01 UTC, merged