Iter9
LobovVit/metric-collector pull request #15
Opened 2024-01-26 12:52 UTC by LobovVit

iter9

2024-01-30 06:26 UTC, Nikscorp requested changes
Оставил замечания в комментариях к pr

2024-01-30 06:26 UTC, Nikscorp commented on internal/agent/app/agent.go
> +	"github.com/LobovVit/metric-collector/internal/agent/logger"
есть server/logger, есть agent/logger — и все они инициализируются в разных местах (один в cmd, другой в internal). Выглядит очень неаккуратно. Зачем так?

Почему не может быть одного пакета logger?

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/domain/memstorage/memstorage.go
> +	tfile.Close()
ошибка закрытия файла не обрабатывается

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/domain/memstorage/memstorage.go
> +	err = json.Unmarshal(data, ms)
лучше анмаршалить в отдельную структуру (можно временную) только с нужными полями и с четко прописанными json тегами. Маршалить аналогично.

Иначе тут можно разные спецэффекты получить в будущем (сделаешь например еще одно поле публичное случайно)

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/logger/logger.go
> +	loggingResponseWriter struct {
а почему это должно быть в одном пакете с логгером? Да еще и в одном файле с ним?

Положил бы в internal/rest/middleware/logger и compress бы туда же засунул

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/logger/logger.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
Можно сделать Write без вызова WriteHeader — и тогда нужно залакировать 200-й код (тк он и вернется). У тебя залогируется 0

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/server/router.go
> +func GetApp(config *config.Config) *App {
это должно называться NewApp. И кстати, а почему app? Это же server слой, а не application.

Я бы сделал:
- `type Server struct`
- `GetApp` -> `New`
- `RouterRun` -> `Run`

и тогда использование будет предельно логичным:

```go
srv := server.New(...)
err := srv.Run()
...
```

а сейчас какая-то каша

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/server/router.go
> +	a.storage.RunPeriodicSave(a.config.FileStoragePath)
а почему сервер решает, когда сторожу запустить PeriodicSave? Почему нельзя это делать в методе New или Start стораджа и запускать в cmd?

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/server/updatejsonhandler.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
return.

Получается на это нет юнита, нужно добавить.
Посмотри заодно coverage и покрой то, что не покрыто (в разумных пределах)

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/server/singlemetricjsonhandler.go
> +	"net/http"
импорты неотсортированы. Настрой в своей IDE использование goimports

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/server/router.go
> +	g, gCtx := errgroup.WithContext(ctx)
кажется WithContext тут излишен, достаточно просто err-группы

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/domain/actions/storage.go
> +func (r *Repo) RunPeriodicSave(filename string) {
а вот это как раз не Run, а Start.

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/domain/actions/storage.go
> +	logger.Log.Info("GetRepo", zap.String("GetRepo", filename), zap.Bool("needRestore", needRestore))
поля то с большой то с маленькой буквы

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/domain/actions/storage.go
> +				logger.Log.Info("periodic save failed", zap.Error(err))
почему это Info, а не Warn / Error?

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/domain/actions/chekandsave.go
> +			logger.Log.Info("immediately save failed", zap.Error(err))
а это почему Info, а не Error?

2024-01-30 06:26 UTC, Nikscorp commented on internal/server/compress/compressmiddleware.go
> +package compress
нет смысла называть файлик аж compressmiddleware.go, он же и так в пакете compress. Почему не просто middleware.go?

2024-01-30 10:01 UTC, LobovVit commented on internal/agent/app/agent.go
> +	"github.com/LobovVit/metric-collector/internal/agent/logger"
logger вынес в общий pkg 
инициатив логера перенес в cmd везде

2024-01-30 10:03 UTC, LobovVit commented on internal/server/domain/memstorage/memstorage.go
> +	tfile.Close()
добавил

2024-01-30 10:08 UTC, LobovVit commented on internal/server/logger/logger.go
> +	loggingResponseWriter struct {
перенес

2024-01-30 10:10 UTC, LobovVit commented on internal/server/domain/actions/storage.go
> +func (r *Repo) RunPeriodicSave(filename string) {
переименовал

2024-01-30 10:15 UTC, LobovVit commented on internal/server/domain/actions/chekandsave.go
> +			logger.Log.Info("immediately save failed", zap.Error(err))
поменял на error

2024-01-30 10:20 UTC, LobovVit commented on internal/server/compress/compressmiddleware.go
> +package compress
переименовал и перенес в "server/middlewares"

2024-01-30 10:25 UTC, LobovVit commented on internal/server/domain/actions/storage.go
> +				logger.Log.Info("periodic save failed", zap.Error(err))
поменял на error

2024-01-30 10:44 UTC, LobovVit commented on internal/server/server/singlemetricjsonhandler.go
> +	"net/http"
настроил

2024-01-30 10:58 UTC, LobovVit commented on internal/server/server/router.go
> +func GetApp(config *config.Config) *App {
переименовал

2024-01-30 17:49 UTC, LobovVit commented on internal/server/server/router.go
> +	g, gCtx := errgroup.WithContext(ctx)
подправил

2024-01-30 20:00 UTC, LobovVit commented on internal/server/domain/actions/storage.go
> +	logger.Log.Info("GetRepo", zap.String("GetRepo", filename), zap.Bool("needRestore", needRestore))
подправил

2024-01-30 20:14 UTC, LobovVit commented on internal/server/domain/memstorage/memstorage.go
> +	err = json.Unmarshal(data, ms)
поправил

2024-01-30 21:00 UTC, LobovVit commented on internal/server/server/router.go
> +	a.storage.RunPeriodicSave(a.config.FileStoragePath)
перенес в "memstorage"

2024-01-30 21:43 UTC, LobovVit commented on internal/server/logger/logger.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
сделал

2024-01-31 09:56 UTC, LobovVit commented on internal/server/server/updatejsonhandler.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
добавил

2024-01-31 09:57 UTC, LobovVit commented on internal/server/logger/logger.go
> +func (r *loggingResponseWriter) Write(b []byte) (int, error) {
сделал

2024-02-02 13:48 UTC, Nikscorp commented on internal/server/compress/compressmiddleware.go
> +package compress
вроде middleware неисчислимое в английском, поэтому должно быть просто middleware

2024-02-02 13:59 UTC, Nikscorp approved these changes
Хорошая работа над ошибками, работа принята

2024-02-02 13:59 UTC, Nikscorp commented on internal/server/server/middlewares/logger.go
> +		logger.Log.Info("Handler log",
логировать лучше в defer-е, чтобы даже при панике в хэндлере оставался лог

2024-02-02 14:08 UTC, merged