Iter13
LobovVit/metric-collector pull request #19
Opened 2024-02-11 16:09 UTC by LobovVit

iter13

2024-02-13 18:36 UTC, Nikscorp requested changes
Оставил замечания в комментариях к pr

2024-02-13 18:36 UTC, Nikscorp commented on internal/agent/app/agent.go
> +	for sendCounter := 1; sendCounter <= 5; sendCounter = sendCounter + 2 {
как-то жестко, можно написать по красивей — вынеся retry и backoff логику в отдельный пакет.

В opensourse есть много пакетов на подобную тему — можешь посмотреть их.
В данном pr править необязательно, просто как точка улучшения

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/domain/dbstorage/dbstorage.go
> +func (ms *DBStorage) SetGauge(key string, val float64) error {
не дело, что контекст из реквеста не доходит до сюда, во всех io операциях прикидывать контекст — обязательно

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/domain/dbstorage/dbstorage.go
> +	createSQL := `create table IF NOT EXISTS metrics (ID text PRIMARY KEY,MType text, Delta bigint, Value double precision)`
индексы бы еще посоздавать

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/domain/dbstorage/dbstorage.go
> +		logger.Log.Error("Get db connection failed", zap.Error(err))
а почему нет return-а? Конструктор тут должен вернуть ошибку

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/domain/dbstorage/dbstorage.go
> +		return fmt.Errorf("upsert failed: %w", err)
в тексте ошибок не должно быть слова failed https://github.com/uber-go/guide/blob/master/style.md#error-wrapping

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/domain/dbstorage/dbstorage.go
> +	selectSQL := `select id, MType, coalesce(Delta,-1), coalesce(Value,-1) from metrics where MType = $1 and id = $2`
лучше объявлять их как const, тогда у линтеров будет больше возможности найти тут ошибку

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/domain/retry/retry.go
> +	if errors.As(err, &pgErr) && pgerrcode.IsConnectionException(pgErr.Code) {
получается тут тесная связь именно с pg, так что пакет должен находится где-то под dbstorage

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/domain/retry/retry.go
> +func (re *Retry) addIteration(delta int) {
тоже выглядит слишком хардкодно — погубил как делают linear backoff в golang (или где угодно)

2024-02-13 18:36 UTC, Nikscorp commented on internal/server/server/middleware/logger.go
> +	r.responseData.status = statusCode // захватываем код статуса
давай уберем русский язык из кода

2024-02-13 18:36 UTC, Nikscorp commented on pkg/postgresql/postgresql.go
> +		logger.Log.Error("DB open failed", zap.Error(err))
логировать лучше уровнем выше, а тут возвращать завраппанную ошибку

2024-02-15 12:06 UTC, LobovVit commented on internal/agent/app/agent.go
> +	for sendCounter := 1; sendCounter <= 5; sendCounter = sendCounter + 2 {
вынес в pkg retry для агента и сервера

2024-02-15 12:07 UTC, LobovVit commented on internal/server/domain/dbstorage/dbstorage.go
> +func (ms *DBStorage) SetGauge(key string, val float64) error {
поправил

2024-02-15 12:18 UTC, LobovVit commented on internal/server/domain/dbstorage/dbstorage.go
> +	createSQL := `create table IF NOT EXISTS metrics (ID text PRIMARY KEY,MType text, Delta bigint, Value double precision)`
добавил  на id,MType

2024-02-15 12:19 UTC, LobovVit commented on internal/server/domain/dbstorage/dbstorage.go
> +		logger.Log.Error("Get db connection failed", zap.Error(err))
добавил

2024-02-15 12:21 UTC, LobovVit commented on internal/server/domain/dbstorage/dbstorage.go
> +		return fmt.Errorf("upsert failed: %w", err)
исправил

2024-02-15 12:21 UTC, LobovVit commented on internal/server/domain/dbstorage/dbstorage.go
> +	selectSQL := `select id, MType, coalesce(Delta,-1), coalesce(Value,-1) from metrics where MType = $1 and id = $2`
сделал

2024-02-15 12:21 UTC, LobovVit commented on internal/server/domain/retry/retry.go
> +func (re *Retry) addIteration(delta int) {
вынес в pkg retry для агента и сервера

2024-02-15 12:22 UTC, LobovVit commented on internal/server/server/middleware/logger.go
> +	r.responseData.status = statusCode // захватываем код статуса
исправил

2024-02-15 12:23 UTC, LobovVit commented on pkg/postgresql/postgresql.go
> +		logger.Log.Error("DB open failed", zap.Error(err))
исправил

2024-02-15 12:46 UTC, LobovVit commented on internal/server/domain/retry/retry.go
> +	if errors.As(err, &pgErr) && pgerrcode.IsConnectionException(pgErr.Code) {
перенес проверку на необходимость retry в db/mem storage

2024-02-17 15:27 UTC, Nikscorp approved these changes
Недочеты по retry еще остались, но работу принимаю.

В целом можно идти сдавать следующие инкременты, особенно если чувствуешь что времени не хватает.

2024-02-17 15:27 UTC, Nikscorp commented on pkg/retry/retry.go
> +func (re *Retry) Run() bool {
очень сложно понять семантику здесь. То есть при true — мы должны перестать ретраить, а при false наоборот заретраить. Еще эта штука делает sleep, который почему-то называется timer)

В общем, пакет пока очень неудачный, но придраться я не буду и закрою на это глаза.
Обычно ретраи делают через через передачу в него функций выполняющих непосредственно бизнес логику и функции определяющей нужно ли что-то ретраить. Также задаются опции backoff-а и колиества ретраев.

Посмотри например сюда https://github.com/avast/retry-go/blob/master/retry.go (это первое что попадается в гугле, выглядит сносно)

2024-02-17 15:27 UTC, Nikscorp commented on internal/server/domain/actions/chekandsave.go
> +			if ret == nil || try.Run() || !r.storage.IsRetryable(ret) {
Вычисления по || — ленивые, ты сначала делаешь Run, который сделает sleep, а потом уже проверяешь нужно ли было ретраить ошибку

2024-02-17 18:28 UTC, merged