Iter15
LobovVit/metric-collector pull request #23
Opened 2024-02-23 13:45 UTC by LobovVit

2024-02-29 03:39 UTC, Nikscorp requested changes
Оставил комментарии в pr

2024-02-29 03:39 UTC, Nikscorp commented on internal/agent/app/agent.go
> +			go m.GetMetricsRuntime()
очень сомнительно, подразумевалось, конечно, что у тебя будет 2 горутины, одна в форе читает метрики по Рид-тикеру, вторая шлет.

А не горутина на каждый тик.

Чтение же runtime и gops как будто нет смысла разбивать на горутины

2024-02-29 03:39 UTC, Nikscorp commented on internal/agent/app/agent.go
> +				sem.acquire()
тут тоже все не так, подразумевалось, что ты рейт-лимитишь исходящие http запросы.

Для случая json и text ты шлешь их в цикле синхронно, а нужно конкурентно но с rate-лимитером.

Для случая batch-а по-хорошему надо тоже разбивать на несколько подзапросов с учетом максимального размера батча, но пока можно слать одним запросом (в таком случае рейт-лимит на него не нужен

2024-02-29 03:39 UTC, Nikscorp commented on internal/server/server/middleware/signature.go
> +				body, _ := io.ReadAll(r.Body)
почему ошибка игнорируется?

2024-02-29 12:34 UTC, LobovVit commented on internal/agent/app/agent.go
> +			go m.GetMetricsRuntime()
переделал

2024-02-29 12:34 UTC, LobovVit commented on internal/agent/app/agent.go
> +				sem.acquire()
переделал

2024-02-29 12:35 UTC, LobovVit commented on internal/server/server/middleware/signature.go
> +				body, _ := io.ReadAll(r.Body)
исправил

2024-03-03 16:55 UTC, Nikscorp requested changes
пока реализация concurrency очень неаккуратная, написал еще замечаний

2024-03-03 16:55 UTC, Nikscorp commented on internal/agent/app/agent.go
> +					sem.release()
чтобы в каждой точке выхода это не писать — есть defer

2024-03-03 16:55 UTC, Nikscorp commented on internal/agent/app/agent.go
> +		wg.Done()
эм, это вообще неправильное использование waitgroup-ы, defer wg.Done() должна делать горутина, иначе в это ноль смысла

2024-03-03 16:55 UTC, Nikscorp commented on internal/agent/app/agent.go
> +				ret = fmt.Errorf("send request: %w", err)
здесь у тебя рейс

2024-03-03 16:55 UTC, Nikscorp commented on internal/agent/app/agent.go
> +			err := func() error {
зачем здесь анонимная функция? Ты же уже внутри функции

2024-03-03 16:55 UTC, Nikscorp commented on internal/agent/app/agent.go
> +	sem := newSemaphore(a.cfg.RateLimit)
зачем sem создавать тут, а не ниже где он нужен

2024-03-03 16:55 UTC, Nikscorp commented on internal/agent/app/agent.go
> +	go func() {
то что ниже тоже красивей запустить в своей горутине, добавить wait-group-у и сделать wait

2024-03-03 17:53 UTC, LobovVit commented on internal/agent/app/agent.go
> +					sem.release()
подправил

2024-03-03 17:53 UTC, LobovVit commented on internal/agent/app/agent.go
> +		wg.Done()
подправил

2024-03-03 17:59 UTC, LobovVit commented on internal/agent/app/agent.go
> +	sem := newSemaphore(a.cfg.RateLimit)
перенес

2024-03-03 18:13 UTC, LobovVit commented on internal/agent/app/agent.go
> +	go func() {
исправил

2024-03-03 20:03 UTC, LobovVit commented on internal/agent/app/agent.go
> +				ret = fmt.Errorf("send request: %w", err)
исправил

2024-03-03 20:03 UTC, LobovVit commented on internal/agent/app/agent.go
> +			err := func() error {
исправил

2024-03-05 08:19 UTC, Nikscorp approved these changes
Написал еще несколько замечаний, но уже готов поставить аппрув

2024-03-05 08:19 UTC, Nikscorp commented on internal/agent/app/agent.go
> +	sem := newSemaphore(a.cfg.RateLimit)
если ты используешь errgroup-ы, что в целом хорошая идея, самому семафор создавать не нужно. У нее уже есть https://pkg.go.dev/golang.org/x/sync/errgroup#Group.SetLimit где под капотом тот же самафор.

2024-03-05 08:19 UTC, Nikscorp commented on internal/agent/app/agent.go
> +		g.Go(func() error {
ты делаешь sem.acquire уже после входа в горутину и получается ы сразу запустишь len(met.Metrics) горутин, что в общем случае может быть проблемой и вызвать переполнение стека.

Так как здесь у нас число метрик ограничено это менее критично, но стоит поправить в любом случае

2024-03-05 08:49 UTC, merged