Iter23
LobovVit/metric-collector pull request #31
Opened 2024-05-21 11:47 UTC by LobovVit

Iter23

2024-05-27 03:50 UTC, Nikscorp requested changes
Оставил замечания к работе, нужно поправить

2024-05-27 03:50 UTC, Nikscorp commented on internal/agent/config/JSONConfig.go
> +package config
файлы в go обычно называют в snake_case, не в PascalCase

2024-05-27 03:50 UTC, Nikscorp commented on internal/server/server/middleware/crypto.go
> +			priv, err := cryptorsa.LoadPrivateKey(filepath)
очень неэффективно на каждый запрос читать сертификат с диска. Чтение должно происходить единственный раз

2024-05-27 03:50 UTC, Nikscorp commented on internal/server/server/middleware/crypto.go
> +				w.WriteHeader(http.StatusBadRequest)
было бы неплохо в body еще писать причину ошибки

2024-05-27 03:50 UTC, Nikscorp commented on internal/server/server/middleware/crypto.go
> +func RsaMiddleware(filepath string) func(http.Handler) http.Handler {
RSA

2024-05-27 03:50 UTC, Nikscorp commented on srv.json
> +}
не хватает переноса строки в конце файла

2024-05-27 03:50 UTC, Nikscorp commented on internal/server/server/server.go
> +	if a.config.CryptoKey != "" {
замечания по gracefulShutdown (сам код которого ниже):
- в shutdown передается уже отмененный контекст
- при стартовой ошибке listenAndServe (например занятый порт) процесс зависнет до получения сигнала
- объединение shutdown и serve в одну errgroup-у неудачное. Ошибка shutdown-а проигнурируется
- Даже при валидном замечании по errServer closed ты напишешь лог с ошибкой. Лучше разделять ожидаемое и ошибочное завершение на info и err уровни

2024-05-27 06:28 UTC, LobovVit commented on internal/agent/config/JSONConfig.go
> +package config
подправили

2024-05-27 13:32 UTC, LobovVit commented on internal/server/server/middleware/crypto.go
> +			priv, err := cryptorsa.LoadPrivateKey(filepath)
подправил

2024-05-27 13:32 UTC, LobovVit commented on internal/server/server/middleware/crypto.go
> +				w.WriteHeader(http.StatusBadRequest)
подправил

2024-05-27 13:33 UTC, LobovVit commented on srv.json
> +}
подправил

2024-05-27 13:37 UTC, LobovVit commented on internal/server/server/server.go
> +	if a.config.CryptoKey != "" {
подправил

2024-05-30 07:38 UTC, Nikscorp approved these changes
Оставил еще замечание. Но работа принята. Поправить можно в рамках следующего спринта

2024-05-30 07:38 UTC, Nikscorp commented on internal/server/server/server.go
> +		a.Shutdown(httpServer)
тут все еще что-то странное. После ошибки listenAndServe (например занятый порт) — ты просто зависнешь на wait-е. Предлагается просто вынести shutdown из errgroup-ы, зачем он там?

2024-05-30 10:54 UTC, merged